# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c5f5eafc6f1cb5bfbce08e5d6eb14ab3e95b6e10249a187c6e8bf4ae5cabaf32ba6790b9ff482cb3c84cea0c426a60a69f9c152461d5224585982cdfa53e06e

test:
  secret_key_base: d7769ce8f5f2a1711ae90342be266b9e7a96efbe4c0e531c6efbda37d0a2fa47e381805c4a2a61a3fc944eca8cafbbe9572cd5598b9930823466b508209f07bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
